/* Copyright (C) 2012-2013 Justin Berger 
   The full license is available in the LICENSE file at the root of this project and is also available at http://opensource.org/licenses/MIT. */

/* 
   DO NOT EDIT THIS FILE. This file is automatically generated via CMake, and any modifications will be overwritten on the next build. If you are using the CMake system in place, you likely want to ENABLE_FEATURE/DISABLE_FEATURE there instead. 

   If you aren't using CMAKE for some reason, note that changing the directives below requires you to rebuild rikitiki from source, or you will likely have references missing.
 */

#pragma once

#define RT_USE_CEF 1
#define RT_USE_LOG 1

